version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2015

before_build:
  - nuget sources Add -Name "Habitat.Coveo" -Source "%HabitatCoveoNuGetSourceUrl%" -username %HabitatCoveoNuGetSourceUsername% -password %HabitatCoveoNuGetSourceAuthToken%
  - nuget install "Coveo.Framework" -Source "Habitat.Coveo" -Version 4.0.1088.0 -OutputDirectory ".\packages"
  - md .\lib
  - md .\lib\Coveo
  - mv .\packages\Coveo.Framework.4.0.1088.0\lib\net45\*.dll .\lib\Coveo
  - cd .\lib\Coveo
  - dir
